version: '3.9'

services:

  mysql:
    image: mysql:5.7.34
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 1G
    restart: always
    ports:
      - 8081:80